#logging.level.org.apache.coyote.http11=debug
spring.messages.basename=messages,errors

server.servlet.session.tracking-modes=cookie
# 1800\uCD08 \uCD5C\uC18C\uB85C \uC124\uC815\uD560 \uC218 \uC788\uB294 \uC2DC\uAC04\uC740 60\uCD08
server.servlet.session.timeout=60